app:
  port: 8000      #服务端口
  apkPath: ./apk/game-xh-release.apk #防红APK路径 注意更新apk时apk名字不能与之前的相同 因为系统缓存了一些文件
  updateInterval: 20       #apk更新间隔 单位秒
  replacePackageName:  false    # 是否自动替换包名
log:
  file: temp/log       #日志目录
  level: info          #trace debug info warning error fatal panic  日志级别
  colour: true         #日志控制台是否显示不同颜色




#apk下载地址
# Walle渠道包    域名/guide/channel/download/渠道id/apk名称.apk
# 非渠道包       域名/guide/download/apk名称.apk
